export const screens = {
  signIn: "sign-in",
  signInWelcome: "sign-in/welcome",
  signUp: "sign-up",
  forgotPassword: "forgot-password",
  onboarding: "onboarding",
  home: "home",
  calendar: "calendar",
  archives: "home/archives",
  newEvent: "home/events/create",
  event: (id: Identifier) => `event/${id}`,
  eventSummary: (id: Identifier) => `event/${id}/summary`,
  eventSettings: (id: Identifier) => `event/${id}/settings`,
  editLocations: (id: Identifier) => `event/${id}/summary/edit-locations`,
  addLocation: (id: Identifier) => `event/${id}/summary/add-location`,
  addPool: (id: Identifier) => `event/${id}/summary/add-pool`,
  addBudget: (id: Identifier) => `event/${id}/summary/add-budget`,
  editGuests: (id: Identifier) => `event/${id}/summary/edit-guests`,
  editDates: (id: Identifier) => `event/${id}/summary/edit-dates`,
  editImportantMsg: (id: Identifier) =>
    `event/${id}/summary/edit-important-msg`,
  editNotes: (id: Identifier) => `event/${id}/summary/edit-notes`,
  editPools: (id: Identifier) => `event/${id}/summary/edit-pools`,
};
