export const screens = {
  signIn: "sign-in",
  signUp: "sign-up",
  forgotPassword: "forgot-password",
  onboarding: "onboarding",
  home: "home",
  calendar: "calendar",
  archives: "home/archives",
  newEvent: "home/events/create",
  event: (id: string) => `event/${id}`,
  eventSummary: (id: string) => `event/${id}/summary`,
  editLocation: (id: string) => `event/${id}/summary/edit-location`,
  editGuests: (id: string) => `event/${id}/summary/edit-guests`,
  editDates: (id: string) => `event/${id}/summary/edit-dates`,
  editImportantMsg: (id: string) => `event/${id}/summary/edit-important-msg`,
  editNotes: (id: string) => `event/${id}/summary/edit-notes`,
};
